### ISSUE TITLE
Viz not working

### ISSUE THREAD

**Issue by jeroenputtevils** [huyen-nguyen/maker#16]
Hi, 
i uploaded my own data in csv. This seems to work but no viz is shown. Under WordStream, I just get a white field...

**Comment by huyen-nguyen** [comment]
Hi @jeroenputtevils, thank you for reaching out!
Can you provide more information so I can investigate further what the error is about? e.g.,
- The browser you used
- The format of your input file (snippet would be great, but that's optional) and encoding of the file.

There was an instance with a certain input where it didn't work on Chrome, but it work on Safari. If you could test it on other browsers, that would be great. Please let me know.

**Comment by huyen-nguyen** [comment]
Hi @jeroenputtevils, thank you for reaching out!
Can you provide more information so I can investigate further what the error is about? e.g.,
- The browser you used
- The format of your input file (snippet would be great, but that's optional) and encoding of the file.

There was an instance with a certain input where it didn't work on Chrome, but it worked on Safari. If you could test it on other browsers, that would be great. Please let me know.

**Comment by jeroenputtevils** [comment]
MS Edge
csv (comma as separator), UTF-8
(Snippet: column headers + first data line)
letters._id,letters.addressee_id,letters.comments,letters.dates.of_arrival,letters.dates.of_departure,letters.dates.of_writing,Year,letters.departure.country,letters.departure.place,letters.destination.country,letters.destination.place,letters.free_annotations,letters.links.to_digital_text,letters.number_of_hands,letters.paraphrases,letters.publication.author_first_name,letters.publication.author_last_name,letters.publication.page_range,letters.publication.title,letters.publication.year,letters.sender_id,letters.text,letters.user
JP_Kamp_001_15720828,608157eeb0e0a7f628bc52d0,,,,28-08-1572,1572,France,Calais,Germany,Hamburg,,http://resolver.kb.nl/resolve?urn=MMSFUBA02:000015415:00008,1,,Jeroen,Nanninga Uitterdijk,,Een Kamper Handelshuis Te Lissabon,1904,608157eeb0e0a7f628bc52ce,"V breff van 23 August ontfangen end verstan  dat/als doe noch neit geladen was  noch neit gedan was./My verwondert dat al de schepen syn wech gezeillet /sonder neit darop geladen tho hebben. Van de bevrachtinge vant scip mit masten mocht nu laten/berosten  und dar neit in duen thott op onse avis./Ghy behorden Jochem Grip end al de werltt neit tho/kennen gegeuen hebben  dat ghy masten laden willen /nu sollen syt tselue gan duen und sollen dar tho/Lixboa so. voell masten jagen  dat sy sollen liggen/ende verrotten dar. Summa wat wy dor v auis willen/duen  dat hangtt ghij ande kloek van de carck. Van/Polne end bussen is off  is ock the ladtt, wat wy/van mening fordtan syn sollen  sall Cunartorff off/yck an v off an Jochum Grip schriuen. By myn vorgande geschreuen dat myn soen well reisen mach /schriue an hem neit  ouermits yck denck hy all/vandar syn sall. Wilt v ergens in en herberch begeuon /dar ghy raar 4 off 5 st. dagl. verterdt  off 40 off 50/dalers sjars  by ein gudt borger end verhout u dar/thott op ons auizo. Wat Piter van der Mor v ordi-/nerdtt  wilt folgen en holt v dingen still, watt ghy/duett duett mytt weinech romors./De nagelen mochtt v de rest guidtt maken  all/wardtt mar om 42 schillingen end de kist ladtt de dar/blijven thott op myn auis./Ik ligge hier tho Gales mit myn swager Jost Rog-/man  om morgen tseill tho gan na Lixboa op een/Frans scip, de wint is goedt  de Heer wil ons allen/bewaren end sine genade verlenen ther salicheit Amen./Is myn soen dar noch  grudt hem my ser end/gebeidtt my ser an myn gueden here Adrian Paw/end an syn l. huysfrow end alle gude vrunden tho/Hamborch. Dezen ingelachten geeft Her Jochim Gripp./Schriff op Lixboa als dar ossen sindtt. Vale ut supra./Hans Snel  iunior./lek segge noch  watt ghy duet dar  off duen willt /duedt secretlix  datt ist principaell van alle comenscap,/off V Piter van der Mor schriff om einige guderen/tho arrestiren de van Vlissinge komen mochten  willt/dar in sin order volgen end alles secretlick duen so/veil alst moglick is  sonder alleman de sack tho rela-/tiren  end ist moglick dat nymant wiste dat ghy van/onzent wegen sulkes deden  wilde wall. Ja wilde/wall dat niemant wiste dat ghy van onzent wegen/the Hamborch syn  behaluen Adrian Paw. In fin/holde alles int secret so vill hett muglick is./An den Ersamen/Jan Jansen thus/mit Peter/touslager tegen de borze/thott/Hamborch./1572 vydt Calis jn Vranckrick/den 20 Augusti. Jn Hamborch den 18 September.",jeroen

**Comment by ncarboni** [comment]
I have the same issue across different browsers. The console output is
```
[Error] TypeError: t.charCodeAt is not a function. (In 't.charCodeAt(u-1)', 't.charCodeAt' is undefined)
	n (d3.v4.min.js:2:31363)
	parse (d3.v4.min.js:2:31713)
	tsvRead (data-loader.js:276)
	(anonymous function) (data-loader.js:86)
	(anonymous function) (d3.v4.min.js:2:8203)
```

**Comment by huyen-nguyen** [comment]
Thanks, @jeroenputtevils & @ncarboni for letting me know, I appreciate the details.
I need some time to look into it. Will definitely update you later!

**Comment by huyen-nguyen** [comment]
Hello and hope y'all doing well, @jeroenputtevils and @ncarboni. It's been a while! 
The above issue is fixed, please let me know if it works for you.

Huyen
